name: courto
description: "courto app"

publish_to: 'none' 


version: 2.1.6+10

environment:
  sdk: ^3.8.1
  

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  geolocator: ^11.0.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  table_calendar: ^3.2.0
  bcrypt: ^1.1.3
  google_maps_flutter: ^2.13.1
  custom_info_window: ^1.0.1
  onesignal_flutter: ^5.3.4
  flutter_launcher_icons: ^0.14.4
  flutter_dotenv: ^6.0.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  carousel_slider: ^5.1.1
  package_rename: ^1.10.0
  moamalat_payment: ^2.0.0
  provider: ^6.1.5+1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  generate: true
  uses-material-design: true


  assets:
    - .env
    - assets/images/courtoFull.png
    - assets/images/courto.png
    - assets/images/courtoFootballSprite.png
    - assets/images/courtoBasketballSprite.png
    - assets/images/courtoTennisSprite.png
    - assets/images/courtoPadelSprite.png
    - assets/images/courtoDefaultHeader.jpg
    - assets/images/courtoTeams.jpg
    - assets/images/courtoChess.png
    - assets/map_styles/dark_map.json
  fonts:
    - family: Changa
      fonts:
        - asset: assets/Changa-SemiBold.ttf
          weight: 600


flutter_launcher_icons: 
  flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/courtoWhiteBackground.png"
  adaptive_icon_background: "#FFFFEBEE"  # or a color hex
  adaptive_icon_foreground: "assets/images/courtoWhiteBackground.png"
  remove_alpha_ios: true


package_rename_config:
  android:
    app_name: "courto"
    package_name: "ly.courto.user"

  ios:
    app_name: "courto"
    bundle_name: "courto"
    package_name: "ly.courto.user"

